// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "c3ba3142-d83a-4e75-a61d-a30c214060b7";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSocket1EnableChange();
void onSocket2EnableChange();
void onSocket3EnableChange();
void onSocket1ScheduleMorningChange();
void onSocket2ScheduleMorningChange();
void onSocket3ScheduleMorningChange();
void onSocket1Change();
void onSocket2Change();
void onSocket3Change();

int socket_1_enable;
int socket_2_enable;
int socket_3_enable;
CloudSchedule socket_1_schedule_morning;
CloudSchedule socket_2_schedule_morning;
CloudSchedule socket_3_schedule_morning;
bool socket_1;
bool socket_2;
bool socket_3;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(socket_1_enable, READWRITE, ON_CHANGE, onSocket1EnableChange);
  ArduinoCloud.addProperty(socket_2_enable, READWRITE, ON_CHANGE, onSocket2EnableChange);
  ArduinoCloud.addProperty(socket_3_enable, READWRITE, ON_CHANGE, onSocket3EnableChange);
  ArduinoCloud.addProperty(socket_1_schedule_morning, READWRITE, ON_CHANGE, onSocket1ScheduleMorningChange);
  ArduinoCloud.addProperty(socket_2_schedule_morning, READWRITE, ON_CHANGE, onSocket2ScheduleMorningChange);
  ArduinoCloud.addProperty(socket_3_schedule_morning, READWRITE, ON_CHANGE, onSocket3ScheduleMorningChange);
  ArduinoCloud.addProperty(socket_1, READWRITE, ON_CHANGE, onSocket1Change);
  ArduinoCloud.addProperty(socket_2, READWRITE, ON_CHANGE, onSocket2Change);
  ArduinoCloud.addProperty(socket_3, READWRITE, ON_CHANGE, onSocket3Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
